# Generated by Django 2.0.7 on 2018-08-21 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaInout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('accion', models.CharField(blank=True, max_length=2, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auditoria_inout',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.SmallIntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.SmallIntegerField()),
                ('is_active', models.SmallIntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContadoresMedicos',
            fields=[
                ('tabla', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('valor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contadores_medicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=3000, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_crea', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diagnosticos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspecialidadesMedicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_crea', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'especialidades_medicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=3000, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_crea', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'examenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(blank=True, null=True)),
                ('inicio', models.TimeField(blank=True, null=True)),
                ('fin', models.TimeField(blank=True, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_crea', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'horarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorariosOcupados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('usuario_crea', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_crea', models.DateTimeField(blank=True, null=True)),
                ('efectiva', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'horarios_ocupados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(blank=True, max_length=2000, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_crea', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
                ('nombre_generico', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'medicamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=3000, null=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('correo', models.CharField(blank=True, max_length=30, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono_casa', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono_oficina', models.CharField(blank=True, max_length=15, null=True)),
                ('aseguradora', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_crea', models.DateTimeField(blank=True, null=True)),
                ('dui', models.CharField(blank=True, max_length=11, null=True)),
                ('direccion', models.CharField(blank=True, max_length=4000, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=1, null=True)),
                ('profesion', models.CharField(blank=True, max_length=4000, null=True)),
                ('empresa', models.CharField(blank=True, max_length=2000, null=True)),
                ('direccion_empresa', models.CharField(blank=True, max_length=4000, null=True)),
                ('municipio', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDiag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=3000, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
                ('fec_crea', models.DateTimeField(blank=True, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'tipo_diag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoExamenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=3000, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_crea', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_examenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=1000)),
                ('nombre', models.CharField(blank=True, max_length=2000, null=True)),
                ('correo', models.CharField(blank=True, max_length=40, null=True)),
                ('clinica', models.CharField(blank=True, max_length=2000, null=True)),
                ('fec_creacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=5, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_cancelado', models.DateTimeField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=45, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id_medico', models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Usuario')),
                ('id', models.IntegerField()),
                ('fecha', models.DateField()),
                ('problema', models.CharField(blank=True, max_length=5000, null=True)),
                ('tratamiento', models.CharField(blank=True, max_length=5000, null=True)),
                ('recomendacion', models.CharField(blank=True, max_length=5000, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('presion_art', models.CharField(blank=True, max_length=20, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_crea', models.DateTimeField(blank=True, null=True)),
                ('observacion_receta', models.CharField(blank=True, max_length=4000, null=True)),
                ('edad_paciente', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consultas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContadorConsultas',
            fields=[
                ('id_medico', models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Usuario')),
                ('valor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contador_consultas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicoEspecialidad',
            fields=[
                ('id_especialidad', models.ForeignKey(db_column='id_especialidad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.EspecialidadesMedicas')),
                ('usuario_crea', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_crea', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medico_especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioErrores',
            fields=[
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Usuario')),
                ('id', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=4000, null=True)),
                ('fec_crea', models.DateTimeField(blank=True, null=True)),
                ('pantalla', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
                ('usuario_resuelve', models.CharField(blank=True, max_length=15, null=True)),
                ('solucion', models.CharField(blank=True, max_length=4000, null=True)),
                ('fec_resuelve', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario_errores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioOlvidaPwd',
            fields=[
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Usuario')),
                ('id', models.IntegerField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('cont_pivote', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'usuario_olvida_pwd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioPagos',
            fields=[
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Usuario')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('dia_prog', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario_pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultasDiag',
            fields=[
                ('id_medico', models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Consultas')),
                ('id_consulta', models.IntegerField()),
                ('usuario_crea', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_crea', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consultas_diag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultasMed',
            fields=[
                ('id_medico', models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Consultas')),
                ('id_consulta', models.IntegerField()),
                ('cantidad', models.CharField(blank=True, max_length=200, null=True)),
                ('forma_uso', models.CharField(blank=True, max_length=3000, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_crea', models.DateTimeField(blank=True, null=True)),
                ('casa', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'consultas_med',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamenesDiag',
            fields=[
                ('id_medico', models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Consultas')),
                ('id_consulta', models.IntegerField()),
                ('usuario_crea', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_crea', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'examenes_diag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('id_medico', models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Consultas')),
                ('id_consulta', models.IntegerField()),
                ('id', models.IntegerField()),
                ('problema', models.CharField(blank=True, max_length=5000, null=True)),
                ('analisis', models.CharField(blank=True, max_length=5000, null=True)),
                ('medico', models.CharField(blank=True, max_length=5000, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=2000, null=True)),
                ('usuario_crea', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_crea', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'referencias',
                'managed': False,
            },
        ),
    ]
